import requests
import time
output_path = "/home/nautilus/python/exersice/urlList.txt"

def get_company_url(company_name, api_key):
    search_url = "https://serpapi.com/search.json"
    params = {
        "q": company_name,
        "location": "United States",
        "hl": "en",
        "gl": "us",
        "api_key": api_key
    }
    
    try:
        response = requests.get(search_url, params=params)
        response.raise_for_status()  # Check if the request was successful
        
        results = response.json()
        
        first_result = results.get('organic_results', [None])[0]
        if first_result:
            return first_result.get('link')
        else:
            return None
    
    except requests.exceptions.HTTPError as http_err:
        print(f"HTTP error occurred: {http_err}")
        if response.status_code == 429:  # Too many requests
            print("Rate limit reached. Waiting before retrying...")
            time.sleep(60)  # Wait for 60 seconds before retrying
            return get_company_url(company_name, api_key)  # Retry the request
        return None
    except requests.exceptions.RequestException as err:
        print(f"Other error occurred: {err}")
        return None
    except (IndexError, KeyError):
        return None

def process_companies_list(companies_list, api_key):
    company_urls = {}
    for company in companies_list:
        url = get_company_url(company, api_key)
        if url:
            company_urls[company] = url
            print(f"Found URL for {company}: {url}")
            with open(output_path, 'a') as file:
                file.write(f"{url}\n")
                file.flush()
        else:
            print(f"Could not find URL for {company}")

    return company_urls

api_key = "api_key" 
companies = ["companies_list"]

company_urls = process_companies_list(companies, api_key)

# Example usage
api_key = "2e09be797ac7dc3f71bac42c66650643f98d9eb068be973a0552760166c4ab9b"  # Replace with your actual SerpAPI key
companies = [
"Deribit",
"Deriv.com",
"Disclosure Assistance",
"Discourse",
"Divvy Homes",
"Django",
"Doppler",
"DuckDuckGo",
"Dynamic Labs",
"Dynatrace",
"Dyson",
"EXNESS",
"Early Warning",
"Ed",
"Egress Software Technologies",
"Elastic",
"Enjin",
"Epic Games",
"Equifax-vdp",
"Eurofins",
"Evernote",
"Exodus",
"Expedia Group",
"Expedia Group Bug Bounty",
"ExpressionEngine",
"FINRA Response",
"FanDuel",
"Faraday, Inc.",
"Fastify",
"Fastly VDP",
"Fertitta Entertainment",
"FetLife",
"Fidelity",
"Fifth Third Bank VDP",
"Figma",
"FileZilla",
"Files.com",
"Fireblocks",
"Fireblocks MPC",
"Flexport VDP",
"Flickr",
"FloQast",
"Flutter UK&I",
"Ford",
"ForeScout Technologies",
"FormAssembly",
"Fossil",
"Fresenius",
"Freshworks",
"Front",
"Frontegg",
"GSA Bounty",
"General Motors",
"GitHub",
"GitHub Security Lab",
"GitLab",
"Glassdoor",
"Global Payments",
"Gmelius",
"GoCD",
"GoCardless Bug Bounty Program",
"GoDaddy VDP",
"Goldman Sachs",
"GoodRx",
"Grab",
"Grammarly",
"Greenfly",
"Greenhouse.io",
"Grindr",
"Gymshark",
"HCL Software Inc.",
"HYPR",
"Hedera Hashgraph",
"Hilton",
"Hiro",
"Home Bargains",
"Hy-Vee",
"Hyatt Hotels",
"Hyperledger",
"IBM",
"IRCCloud",
"Inditex",
"Informatica",
"Instacart",
"Insulet Corporation",
"Inter & Co. VDP",
"International Airlines Group",
"Internet Bug Bounty",
"Intuit",
"InvestNext",
"Invision Power Services, Inc.",
"Ionity GmbH",
"Ivanti (VDP)",
"JNJ Mobile",
"JetBlue",
"John Deere",
"JohnBlackbourn",
"Judge.me",
"KAYAK",
"KKR-VDP",
"KOHO",
"Kahootz",
"Keurig Dr Pepper",
"KeyBank",
"Khan Academy",
"Kindred Group",
"Kiwi.com",
"Klarna",
"Kolesa Group",
"Krisp",
"Kubernetes",
"LATAM Airlines",
"LY Corporation",
"Lab45",
"Lacework",
"Lark Technologies",
"LaunchDarkly",
"Leather Wallet",
"LinkedIn",
"LocalTapiola",
"Localize",
"Logitech",
"Loofah",
"Lowe's Companies VDP",
"LumiraDx",
"Lyst",
"M&T Bank Vulnerability Disclosure",
"MTN Group",
"Magic",
"Magic Eden",
"MainWP",
"Malwarebytes",
"Managed",
"Mapbox",
"MariaDB",
"Marriott Bug Bounty Program",
"Mars",
"Matomo",
"Mattermost",
"Mendix",
"MercadoLibre",
"Merck & Co., Inc., Rahway, NJ, USA",
"Mergify",
"Meta",
"MetaMask",
"Miro",
"Modern Treasury",
"Monarch Money",
"Mondelēz International",
"Monero",
"MongoDB",
"MoonPay",
"Moov",
"Mount Sinai Health",
"Mozilla",
"Myndr",
"NBA",
"NBA Public Bug Bounty",
"NISC-VDP",
"Navient Solutions LLC",
"Netflix",
"Netlify",
"Newegg",
"Nextcloud",
"NiceHash",
"Nimiq",
"Nintendo",
"Node.js",
"Nokogiri",
"Nominet",
"Nord Security",
"Nutanix",
"OANDA",
"OKG",
"ONE ZERO VDP",
"OWOX, Inc.",
"OakNorth Bank",
"Oasis Protocol Foundation",
"Octopus Energy Group",
"Ohio Secretary of State",
"Omise",
"On",
"OpenMage",
"Oportun",
"Overloop",
"PUBG",
"PagerDuty",
"Palantir Public",
"Palo Alto Software",
"Parrot Sec",
"Particle Health VDP",
"PayPal",
"Payoneer",
"Paystack Vulnerability Disclosure",
"Peloton",
"Pfizer",
"Phabricator",
"Picsart",
"Pillar Project Worldwide Limited",
"Ping Identity",
"Plaid",
"Planet Labs",
"PlayStation",
"Playtika",
"Polygon Technology",
"PornBox",
"PortSwigger Web Security",
"Priceline",
"ProductBoard, Inc.",
"Prolinx VDP",
"Prudential Financial",
"Publitas",
"Python Cryptographic Authority",
"Quora",
"R3",
"RATELIMITED",
"REI BBP",
"REI VDP",
"Razorpay",
"Rebellion Defense",
"Recorded Future",
"Reddit",
"Redis",
"Redox",
"Remitly",
"Render",
"Reports",
"ResMed",
"Retesting",
"Revive Adserver",
"Ring",
"Ro",
"Roblox",
"Rockstar Games",
"Rootstock Labs",
"Ruby",
"Ruby on Rails",
"RubyGems",
"S-Pankki",
"SEGA",
"SHEIN",
"SIX Group",
"SKALE Network",
"SMTP2GO BBP",
"SVB Financial",
"Scopely",
"SecurityScorecard",
"Semrush",
"ServiceNow Disclosure",
"Sheer",
"Shipt",
"Shopify",
"Shutterfly VDP",
"SideFX",
"Simple Poll",
"Skinport",
"Slack",
"Smule",
"Snapchat",
"Snowplow",
"Solidus",
"Sony",
"Sorare",
"Spotify",
"Staging.every.org",
"Standard Notes",
"Stanford University",
"Starbucks",
"Starling Bank Limited",
"Stellar.org",
"Stripe",
"Stripo Inc",
"StrongDM",
"Supabase",
"Superbet",
"TD Bank Group",
"TRON DAO",
"Temu",
"Tenable",
"Tennessee Valley Authority",
"Tesco",
"The Walt Disney Company",
"Thnks",
"Thomson Reuters",
"Tide",
"TikTok",
"Tim Hortons VDP",
"TimelyCare",
"Tinder",
"Tools for Humanity",
"Top Echelon Software",
"Tor",
"Toyota",
"TransUnion LLC",
"Trellix",
"Trendyol",
"Trip.com",
"Truecaller",
"Truist Financial",
"U.S. Department of State",
"U.S. Dept Of Defense",
"U.S. General Services Administration",
"UPS VDP",
"USPS - United States Postal Service",
"Uber",
"Ubiquiti Inc.",
"Udemy",
"Urban Company",
"UserTesting",
"Valve",
"Varonis",
"Veeam",
"Vendasta",
"Version Cake",
"Via",
"Vimeo",
"Visa",
"Vodafone Oman",
"WHO COVID-19 Mobile App",
"WakaTime",
"Wealthsimple",
"Weblate",
"WellHive",
"Wells Fargo",
"Wickr",
"Windstream",
"WisdomTree, Inc.",
"WordPress",
"Worklytics",
"X (Formerly Twitter)",
"XVIDEOS",
"Xiaomi",
"Xverse",
"Yahoo!",
"Yelp",
"Yoti",
"Yuga Labs",
"Zabbix",
"Zebra VDP",
"Zendesk",
"ZeroBounce",
"Zomato",
"abb",
"abercrombie_fitch",
"abn_amro_vdp",
"aboitizpower_corporation",
"acronis",
"adobe",
"aeromexico_vdp",
"affirm",
"agoric",
"aig",
"airbnb",
"airtable",
"alchemyplatform",
"allegion",
"alohi",
"alsco",
"alshaya",
"amazonvrp",
"amazonvrp-devices",
"anthropic-vdp",
"anywhererealestate",
"aon",
"apnic",
"arkadiyt-projects",
"arkose_labs",
"aspen",
"att",
"automattic",
"avalara",
"aven_response",
"average",
"banco_bmg",
"basecamp",
"beiersdorf",
"bitmex",
"bitso",
"bitwarden",
"blackrock",
"blend-labs",
"blockchain",
"blueapron",
"bookingcom",
"boozt",
"brave",
"brightspeed",
"bumble",
"bybit_fintech",
"callsign",
"canada_goose_inc",
"capital-one",
"cbre",
"cedars-sinai",
"central-security-project",
"cert",
"chainlink",
"chaturbate",
"chia_network",
"chime",
"circle",
"circle-bbp",
"cirrusinsight",
"city_of_los_angeles_vdp",
"clario",
"clarivate",
"cloudflare",
"clubhouse",
"coalition",
"coda_bbp",
"cognizant",
"coinbase",
"coinhako",
"coinspot",
"compass-bbp",
"concretecms",
"consensys",
"cornershop",
"cosmos",
"costco",
"coursera",
"creditkarma",
"crowdstrike",
"crypto",
"cs_money",
"csg-public",
"curl",
"daimler_truck",
"dashlane",
"databricks",
"datastax",
"date",
"defectdojo",
"deliveryhero",
"deptofdefense",
"deribit",
"deriv",
"dib-vdp",
"disclosure-assistance",
"discourse",
"disney",
"divvy-homes",
"django",
"doppler",
"duckduckgo",
"dynamic_labs",
"dynatrace",
"dyson",
"eMoney Advisor",
"eToro BBP",
"early_warning",
"ed",
"eero",
"egress-vdp",
"elastic",
"emoney-advisor",
"enjin",
"epicgames",
"equifax",
"etoro_bbp",
"eufy Security",
"eufy_security",
"eurofins",
"evernote",
"exness",
"exodus",
"expediagroup",
"expediagroup_bbp",
"expressionengine",
"fanduel",
"faraday_inc",
"fastify",
"fastly-vdp",
"fertitta_entertainment",
"fetlife",
"fidelity",
"fifth_third_bank_vdp",
"figma",
"files",
"filezilla",
"finra",
"fireblocks",
"fireblocks_mpc",
"flexport_vdp",
"flickr",
"floqast",
"flutteruki",
"ford",
"forescout_technologies",
"formassembly",
"fossil",
"fresenius",
"freshworks",
"frontegg",
"fronthq",
"github",
"github-security-lab",
"gitlab",
"glassdoor",
"global-payments",
"gm",
"gmelius",
"gocardless_bbp",
"gocd",
"godaddy-vdp",
"goldmansachs",
"goodrx",
"grab",
"grammarly",
"greenfly",
"greenhouse",
"grindr",
"gsa_bbp",
"gsa_vdp",
"gymshark",
"hcl_software",
"hedera-hashgraph",
"hilton",
"hiro",
"homebargains",
"hostinger",
"hy-vee",
"hyatt",
"hyperledger",
"hypr-corp",
"ibb",
"ibm",
"inDrive",
"inditex",
"indrive",
"informatica",
"instacart",
"insulet_corporation",
"interco_vdp",
"international_airlines_group",
"intuit_rdp",
"investnext",
"ionity_gmbh",
"ips",
"irccloud",
"ivanti_vdp",
"jetblue",
"jnj_mobile",
"john-deere",
"johnblackbourn",
"judgeme",
"kahootz-vdp",
"kayak",
"keurigdrpepper",
"keybank",
"khanacademy",
"kindred_group",
"kiwicom",
"kkr_vdp",
"klarna",
"koho",
"kolesagroup",
"krisp",
"kubernetes",
"lab45",
"lacework",
"lark_technologies",
"latamairlines",
"launchdarkly",
"leather_wallet",
"lemlist",
"line",
"linkedin",
"localizejs",
"localtapiola",
"logitech",
"loofah",
"lowes",
"lumiradx",
"lyst",
"magic-bbp",
"magic-eden",
"mainwp",
"malwarebytes",
"mapbox",
"mariadb",
"marriott",
"mars",
"matomo",
"mattermost",
"mendix",
"mercadolibre",
"mergify",
"meta",
"metamask",
"minimum",
"miro",
"modern_treasury",
"monarch_money",
"mondelez",
"monero",
"mongodb",
"moonpay",
"moov",
"mount-sinai-health",
"mozilla",
"msd",
"mtb",
"mtn_group",
"myndr",
"navient_solutions",
"nba-public",
"nba-vdp",
"netflix",
"netlify",
"newegg",
"nextcloud",
"nicehash",
"nimiq",
"nintendo",
"nisc",
"nodejs",
"nokogiri",
"nominet",
"nordsecurity",
"nutanix",
"oaknorth_bank",
"oanda",
"oasisprotocol",
"octopus-energy",
"ohiosecretaryofstate",
"okg",
"omise",
"on",
"one_zero_vdp",
"openmage",
"oportun_vdp",
"overloop",
"owox",
"pagerduty",
"palantir_public",
"palo_alto_software",
"parrot_sec",
"particle-health-vdp",
"passhash",
"payoneer",
"paypal",
"paystack-vdp",
"peloton",
"pfizer",
"phabricator",
"phpBB",
"phpbb",
"picsart",
"pillarproject",
"pingidentity",
"pixiv",
"plaid",
"planet-labs",
"playstation",
"playtika",
"polygon-technology",
"pornbox",
"portswigger",
"priceline",
"productboard",
"prolinx-vdp",
"prudential-financial",
"pubg",
"publitas",
"pyca",
"quora",
"r3",
"rails",
"ratelimited",
"razorpay",
"rebellion-defense",
"recorded-future",
"reddit",
"redis-vdp",
"redox_bbp",
"rei_bbp",
"rei_vdp",
"remitly",
"render",
"resmed",
"resolved",
"revive_adserver",
"ridewithvia",
"ring",
"ro",
"roblox",
"rockstargames",
"rootstocklabs",
"ruby",
"rubygems",
"s-pankki",
"scopely",
"securityscorecard",
"sega",
"semrush",
"servicenow-disclosure",
"sheer_bbp",
"shein",
"shipt",
"shopify",
"shutterfly_vdp",
"sidefx",
"simple_poll",
"six-group",
"skale_network",
"skinport",
"slack",
"smtp2go",
"smule",
"snapchat",
"snowplow",
"solidus",
"sony",
"sorare",
"spotify",
"stagingdoteverydotorg",
"standard_notes",
"stanford-university",
"starbucks",
"starling_bank",
"stellar",
"stripe",
"stripo",
"strongdm",
"supabase",
"superbet",
"svb-financial",
"td-bank",
"temu",
"tenable",
"tennessee-valley-authority",
"tesco",
"thnks",
"thomsonreuters-public",
"tide",
"tiktok",
"tim_hortons_vdp",
"timelycare",
"tinder",
"toolsforhumanity",
"top_echelon_software",
"torproject",
"toyota",
"transunion",
"trellix",
"trendyol",
"trip_com",
"tron_dao",
"truecaller",
"truist_financial",
"trycourier",
"uber",
"udemy",
"ui",
"ups",
"urbancompany",
"us-department-of-state",
"usertesting",
"usps",
"valve",
"varonis",
"veeam",
"vendasta",
"versioncake",
"vimeo",
"visa",
"vodafone_oman",
"wakatime",
"watson_group",
"wealthsimple",
"weblate",
"wellhive",
"wellsfargo",
"who-covid-19-mobile-app",
"wickr",
"windstream",
"wisdomtree",
"wordpress",
"worklytics",
"x",
"xiaomi",
"xverse",
"xvideos",
"yahoo",
"yelp",
"yoti",
"yuga_labs",
"zabbix",
"zebra_vdp",
"zendesk",
"zerobounce",
"zomato"
]  # Replace with your company list

company_urls = process_companies_list(companies, api_key)
